import {
  BadgeDollarSign,
  CarFront,
  ChartNoAxesCombined,
  CreditCard,
  Landmark,
  PiggyBank,
  Plane,
  Scale,
  WalletCards,
} from "lucide-react";
import type { ModuleDefinition } from "../types/finance";
import {
  calculateAutoLoan,
  calculateBankLoan,
  calculateBreakEven,
  calculateBusinessFeasibility,
  calculateCreditCard,
  calculateMortgage,
  calculateRoi,
  calculateSavings,
  calculateTravelBudget,
} from "../utils/financial";

export const modulesCatalog: ModuleDefinition<Record<string, number>>[] = [
  {
    id: "mortgage",
    name: "Créditos hipotecarios",
    shortName: "Hipotecario",
    description: "Simula mensualidad, intereses y amortización simple para escenarios hipotecarios.",
    icon: Landmark,
    accent: "from-sky to-teal/70",
    category: "business",
    defaults: {
      loanAmount: 2400000,
      annualRate: 10.8,
      termYears: 20,
    },
    fields: [
      { name: "loanAmount", label: "Monto del crédito", kind: "currency", step: 10000 },
      { name: "annualRate", label: "Tasa anual", kind: "percent", step: 0.1 },
      { name: "termYears", label: "Plazo en años", kind: "number", step: 1, min: 1 },
    ],
    calculate: calculateMortgage,
  },
  {
    id: "credit-card",
    name: "Tarjetas de crédito",
    shortName: "Tarjeta",
    description: "Compara un pago objetivo contra el costo de seguir pagando el mínimo.",
    icon: CreditCard,
    accent: "from-amber-300 to-gold",
    category: "personal",
    defaults: {
      balance: 85000,
      annualRate: 48,
      payoffMonths: 24,
      minPaymentRate: 5,
    },
    fields: [
      { name: "balance", label: "Saldo actual", kind: "currency", step: 1000 },
      { name: "annualRate", label: "Tasa anual", kind: "percent", step: 0.1 },
      { name: "payoffMonths", label: "Plazo estimado", kind: "number", step: 1, min: 1 },
      { name: "minPaymentRate", label: "Pago mínimo %", kind: "percent", step: 0.5 },
    ],
    calculate: calculateCreditCard,
  },
  {
    id: "bank-loan",
    name: "Préstamos bancarios",
    shortName: "Préstamo bancario",
    description: "Calcula pago mensual y costo total para préstamos personales o empresariales.",
    icon: WalletCards,
    accent: "from-emerald-300 to-teal/80",
    category: "personal",
    defaults: {
      amount: 180000,
      annualRate: 18.5,
      termMonths: 36,
    },
    fields: [
      { name: "amount", label: "Monto", kind: "currency", step: 5000 },
      { name: "annualRate", label: "Tasa anual", kind: "percent", step: 0.1 },
      { name: "termMonths", label: "Plazo en meses", kind: "number", step: 1, min: 1 },
    ],
    calculate: calculateBankLoan,
  },
  {
    id: "auto-loan",
    name: "Créditos automotrices",
    shortName: "Auto",
    description: "Evalúa enganche, monto financiado y costo final del vehículo.",
    icon: CarFront,
    accent: "from-cyan-300 to-sky",
    category: "personal",
    defaults: {
      vehiclePrice: 520000,
      downPayment: 120000,
      annualRate: 13.9,
      termMonths: 48,
    },
    fields: [
      { name: "vehiclePrice", label: "Valor del auto", kind: "currency", step: 10000 },
      { name: "downPayment", label: "Enganche", kind: "currency", step: 5000 },
      { name: "annualRate", label: "Tasa anual", kind: "percent", step: 0.1 },
      { name: "termMonths", label: "Plazo en meses", kind: "number", step: 1, min: 1 },
    ],
    calculate: calculateAutoLoan,
  },
  {
    id: "travel-budget",
    name: "Presupuesto de viaje",
    shortName: "Viaje",
    description: "Captura categorías clave del viaje y valida remanente o excedente.",
    icon: Plane,
    accent: "from-orange-300 to-amber-300",
    category: "personal",
    defaults: {
      targetBudget: 45000,
      transport: 11000,
      lodging: 14000,
      meals: 7000,
      activities: 5000,
      buffer: 3500,
    },
    fields: [
      { name: "targetBudget", label: "Presupuesto total", kind: "currency", step: 1000 },
      { name: "transport", label: "Transporte", kind: "currency", step: 500 },
      { name: "lodging", label: "Hospedaje", kind: "currency", step: 500 },
      { name: "meals", label: "Comidas", kind: "currency", step: 500 },
      { name: "activities", label: "Actividades", kind: "currency", step: 500 },
      { name: "buffer", label: "Colchón / imprevistos", kind: "currency", step: 500 },
    ],
    calculate: calculateTravelBudget,
  },
  {
    id: "savings",
    name: "Ahorro e instrumentos",
    shortName: "Ahorro",
    description: "Modelo de meta de ahorro con rendimiento y aportaciones periódicas.",
    icon: PiggyBank,
    accent: "from-lime-300 to-emerald-300",
    category: "personal",
    defaults: {
      targetAmount: 300000,
      monthlyContribution: 6500,
      annualRate: 8.5,
      termYears: 3,
      currentSavings: 50000,
    },
    fields: [
      { name: "targetAmount", label: "Meta de ahorro", kind: "currency", step: 5000 },
      { name: "monthlyContribution", label: "Aportación mensual", kind: "currency", step: 500 },
      { name: "annualRate", label: "Tasa estimada", kind: "percent", step: 0.1 },
      { name: "termYears", label: "Plazo en años", kind: "number", step: 1, min: 1 },
      { name: "currentSavings", label: "Ahorro actual", kind: "currency", step: 1000 },
    ],
    calculate: calculateSavings,
  },
  {
    id: "roi",
    name: "Retorno de inversión",
    shortName: "ROI",
    description: "Mide ROI actual y proyección reforzada con aportaciones periódicas.",
    icon: ChartNoAxesCombined,
    accent: "from-violet-300 to-indigo-300",
    category: "business",
    defaults: {
      initialInvestment: 250000,
      finalValue: 360000,
      years: 3,
      periodicContribution: 4000,
    },
    fields: [
      { name: "initialInvestment", label: "Inversión inicial", kind: "currency", step: 5000 },
      { name: "finalValue", label: "Valor final esperado o real", kind: "currency", step: 5000 },
      { name: "years", label: "Horizonte en años", kind: "number", step: 1, min: 1 },
      { name: "periodicContribution", label: "Aportación mensual", kind: "currency", step: 500 },
    ],
    calculate: calculateRoi,
  },
  {
    id: "break-even",
    name: "Punto de equilibrio",
    shortName: "Equilibrio",
    description: "Calcula margen, unidades mínimas y utilidad proyectada por volumen.",
    icon: Scale,
    accent: "from-rose-300 to-orange-300",
    category: "business",
    defaults: {
      fixedCosts: 95000,
      salePrice: 550,
      variableCostPerUnit: 220,
      projectedUnits: 420,
    },
    fields: [
      { name: "fixedCosts", label: "Costos fijos", kind: "currency", step: 1000 },
      { name: "salePrice", label: "Precio de venta", kind: "currency", step: 10 },
      { name: "variableCostPerUnit", label: "Costo variable por unidad", kind: "currency", step: 10 },
      { name: "projectedUnits", label: "Unidades proyectadas", kind: "number", step: 1, min: 1 },
    ],
    calculate: calculateBreakEven,
  },
  {
    id: "business-feasibility",
    name: "Rentabilidad de negocio",
    shortName: "Negocio",
    description: "Evaluación inicial para decidir si el negocio es viable antes de arrancar.",
    icon: BadgeDollarSign,
    accent: "from-fuchsia-300 to-rose-300",
    category: "business",
    defaults: {
      initialInvestment: 420000,
      estimatedMonthlyRevenue: 125000,
      fixedMonthlyCosts: 42000,
      variableMonthlyCosts: 31000,
    },
    fields: [
      { name: "initialInvestment", label: "Inversión inicial", kind: "currency", step: 5000 },
      { name: "estimatedMonthlyRevenue", label: "Ingresos mensuales estimados", kind: "currency", step: 1000 },
      { name: "fixedMonthlyCosts", label: "Costos mensuales fijos", kind: "currency", step: 1000 },
      { name: "variableMonthlyCosts", label: "Costos variables", kind: "currency", step: 1000 },
    ],
    calculate: calculateBusinessFeasibility,
  },
];
