import {
  BadgeDollarSign,
  CarFront,
  ChartNoAxesCombined,
  CreditCard,
  Landmark,
  PiggyBank,
  Plane,
  Scale,
  WalletCards,
} from "lucide-react";
import type { ModuleDefinition } from "../types/finance";
import {
  calculateAutoLoan,
  calculateBankLoan,
  calculateBreakEven,
  calculateBusinessFeasibility,
  calculateCreditCard,
  calculateMortgage,
  calculateRoi,
  calculateSavings,
  calculateTravelBudget,
} from "../utils/financial";

export const modulesCatalog: ModuleDefinition<Record<string, number>>[] = [
  {
    id: "mortgage",
    name: "Creditos hipotecarios",
    shortName: "Hipotecario",
    description:
      "Evalua mensualidad, costo financiero y estructura del credito antes de comprometer un inmueble.",
    icon: Landmark,
    accent: "from-sky to-teal/70",
    category: "business",
    defaults: {
      loanAmount: 2400000,
      annualRate: 10.8,
      termYears: 20,
    },
    fields: [
      {
        name: "loanAmount",
        label: "Monto total del credito",
        kind: "currency",
        step: 10000,
        helper: "Capital total a financiar antes de intereses.",
      },
      {
        name: "annualRate",
        label: "Tasa anual del credito",
        kind: "percent",
        step: 0.1,
        helper: "Tasa anual nominal en porcentaje (%).",
      },
      {
        name: "termYears",
        label: "Plazo del credito en anos",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Tiempo estimado para liquidar el credito.",
      },
    ],
    calculate: calculateMortgage,
  },
  {
    id: "credit-card",
    name: "Tarjetas de credito",
    shortName: "Tarjeta",
    description:
      "Compara una estrategia de pago contra el costo de seguir cubriendo solo el minimo.",
    icon: CreditCard,
    accent: "from-amber-300 to-gold",
    category: "personal",
    defaults: {
      balance: 85000,
      annualRate: 48,
      payoffMonths: 24,
      minPaymentRate: 5,
    },
    fields: [
      {
        name: "balance",
        label: "Saldo actual de la tarjeta",
        kind: "currency",
        step: 1000,
        helper: "Monto pendiente sobre el que se siguen generando intereses.",
      },
      {
        name: "annualRate",
        label: "Tasa anual de la tarjeta",
        kind: "percent",
        step: 0.1,
        helper: "Costo anual aproximado de financiamiento (%).",
      },
      {
        name: "payoffMonths",
        label: "Plazo objetivo para liquidar",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Meses en los que quieres dejar la deuda en cero.",
      },
      {
        name: "minPaymentRate",
        label: "Porcentaje de pago minimo",
        kind: "percent",
        step: 0.5,
        helper: "Referencia del pago minimo requerido por el banco.",
      },
    ],
    calculate: calculateCreditCard,
  },
  {
    id: "bank-loan",
    name: "Prestamos bancarios",
    shortName: "Prestamo bancario",
    description:
      "Calcula cuota, costo total y presion financiera antes de tomar un prestamo personal o empresarial.",
    icon: WalletCards,
    accent: "from-emerald-300 to-teal/80",
    category: "personal",
    defaults: {
      amount: 180000,
      annualRate: 18.5,
      termMonths: 36,
    },
    fields: [
      {
        name: "amount",
        label: "Monto total solicitado",
        kind: "currency",
        step: 5000,
        helper: "Capital que necesitas recibir del banco.",
      },
      {
        name: "annualRate",
        label: "Tasa anual del prestamo",
        kind: "percent",
        step: 0.1,
        helper: "Tasa anual en porcentaje (%).",
      },
      {
        name: "termMonths",
        label: "Plazo del prestamo en meses",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Duracion total del compromiso financiero.",
      },
    ],
    calculate: calculateBankLoan,
  },
  {
    id: "auto-loan",
    name: "Creditos automotrices",
    shortName: "Auto",
    description:
      "Evalua el costo real del vehiculo considerando enganche, financiamiento e intereses.",
    icon: CarFront,
    accent: "from-cyan-300 to-sky",
    category: "personal",
    defaults: {
      vehiclePrice: 520000,
      downPayment: 120000,
      annualRate: 13.9,
      termMonths: 48,
    },
    fields: [
      {
        name: "vehiclePrice",
        label: "Precio total del vehiculo",
        kind: "currency",
        step: 10000,
        helper: "Valor total del auto antes del financiamiento.",
      },
      {
        name: "downPayment",
        label: "Enganche inicial",
        kind: "currency",
        step: 5000,
        helper: "Monto que aportas al inicio para reducir el credito.",
      },
      {
        name: "annualRate",
        label: "Tasa anual del credito",
        kind: "percent",
        step: 0.1,
        helper: "Costo anual del financiamiento (%).",
      },
      {
        name: "termMonths",
        label: "Plazo del credito en meses",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Tiempo estimado para liquidar el auto.",
      },
    ],
    calculate: calculateAutoLoan,
  },
  {
    id: "travel-budget",
    name: "Presupuesto de viaje",
    shortName: "Viaje",
    description:
      "Ordena gastos clave del viaje y valida si el presupuesto alcanza con margen razonable.",
    icon: Plane,
    accent: "from-orange-300 to-amber-300",
    category: "personal",
    defaults: {
      targetBudget: 45000,
      transport: 11000,
      lodging: 14000,
      meals: 7000,
      activities: 5000,
      buffer: 3500,
    },
    fields: [
      {
        name: "targetBudget",
        label: "Presupuesto total disponible",
        kind: "currency",
        step: 1000,
        helper: "Monto maximo que planeas destinar al viaje.",
      },
      {
        name: "transport",
        label: "Gasto estimado en transporte",
        kind: "currency",
        step: 500,
        helper: "Vuelos, gasolina, traslados o movilidad local.",
      },
      {
        name: "lodging",
        label: "Gasto estimado en hospedaje",
        kind: "currency",
        step: 500,
        helper: "Hotel, Airbnb u otras noches de estancia.",
      },
      {
        name: "meals",
        label: "Gasto estimado en comidas",
        kind: "currency",
        step: 500,
        helper: "Consumo planeado en alimentos y bebidas.",
      },
      {
        name: "activities",
        label: "Gasto estimado en actividades",
        kind: "currency",
        step: 500,
        helper: "Tours, entradas o experiencias opcionales.",
      },
      {
        name: "buffer",
        label: "Fondo para imprevistos",
        kind: "currency",
        step: 500,
        helper: "Margen de seguridad para gastos no planeados.",
      },
    ],
    calculate: calculateTravelBudget,
  },
  {
    id: "savings",
    name: "Ahorro e instrumentos",
    shortName: "Ahorro",
    description:
      "Proyecta si tu estrategia actual de ahorro y rendimiento te acerca realmente a la meta.",
    icon: PiggyBank,
    accent: "from-lime-300 to-emerald-300",
    category: "personal",
    defaults: {
      targetAmount: 300000,
      monthlyContribution: 6500,
      annualRate: 8.5,
      termYears: 3,
      currentSavings: 50000,
    },
    fields: [
      {
        name: "targetAmount",
        label: "Meta total de ahorro",
        kind: "currency",
        step: 5000,
        helper: "Monto final que quieres alcanzar.",
      },
      {
        name: "monthlyContribution",
        label: "Aportacion mensual planeada",
        kind: "currency",
        step: 500,
        helper: "Cantidad que podrias ahorrar cada mes.",
      },
      {
        name: "annualRate",
        label: "Rendimiento anual estimado",
        kind: "percent",
        step: 0.1,
        helper: "Rendimiento anual esperado del instrumento (%).",
      },
      {
        name: "termYears",
        label: "Plazo de ahorro en anos",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Tiempo disponible para alcanzar la meta.",
      },
      {
        name: "currentSavings",
        label: "Ahorro acumulado actual",
        kind: "currency",
        step: 1000,
        helper: "Monto con el que ya cuentas hoy.",
      },
    ],
    calculate: calculateSavings,
  },
  {
    id: "roi",
    name: "Retorno de inversion",
    shortName: "ROI",
    description:
      "Mide el retorno esperado y ayuda a juzgar si una inversion compensa el riesgo asumido.",
    icon: ChartNoAxesCombined,
    accent: "from-violet-300 to-indigo-300",
    category: "business",
    defaults: {
      initialInvestment: 250000,
      finalValue: 360000,
      years: 3,
      periodicContribution: 4000,
    },
    fields: [
      {
        name: "initialInvestment",
        label: "Inversion inicial",
        kind: "currency",
        step: 5000,
        helper: "Monto colocado al inicio del proyecto o instrumento.",
      },
      {
        name: "finalValue",
        label: "Valor final esperado o real",
        kind: "currency",
        step: 5000,
        helper: "Valor total estimado al cierre del periodo.",
      },
      {
        name: "years",
        label: "Horizonte de inversion en anos",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Tiempo en el que esperas recuperar y hacer crecer el capital.",
      },
      {
        name: "periodicContribution",
        label: "Aportacion mensual adicional",
        kind: "currency",
        step: 500,
        helper: "Ahorro o capital extra que piensas agregar cada mes.",
      },
    ],
    calculate: calculateRoi,
  },
  {
    id: "break-even",
    name: "Punto de equilibrio",
    shortName: "Equilibrio",
    description:
      "Define el volumen minimo necesario para cubrir costos y empezar a generar utilidad.",
    icon: Scale,
    accent: "from-rose-300 to-orange-300",
    category: "business",
    defaults: {
      fixedCosts: 95000,
      salePrice: 550,
      variableCostPerUnit: 220,
      projectedUnits: 420,
    },
    fields: [
      {
        name: "fixedCosts",
        label: "Costos fijos mensuales",
        kind: "currency",
        step: 1000,
        helper: "Gastos que existen aunque no vendas una unidad.",
      },
      {
        name: "salePrice",
        label: "Precio de venta por unidad",
        kind: "currency",
        step: 10,
        helper: "Ingreso unitario esperado por cada venta.",
      },
      {
        name: "variableCostPerUnit",
        label: "Costo variable por unidad",
        kind: "currency",
        step: 10,
        helper: "Costo directo asociado a cada unidad vendida.",
      },
      {
        name: "projectedUnits",
        label: "Unidades proyectadas a vender",
        kind: "number",
        step: 1,
        min: 1,
        helper: "Volumen que crees posible vender en el periodo.",
      },
    ],
    calculate: calculateBreakEven,
  },
  {
    id: "business-feasibility",
    name: "Rentabilidad de negocio",
    shortName: "Negocio",
    description:
      "Evalua si los ingresos esperados justifican la inversion y el nivel de costo operativo.",
    icon: BadgeDollarSign,
    accent: "from-fuchsia-300 to-rose-300",
    category: "business",
    defaults: {
      initialInvestment: 420000,
      estimatedMonthlyRevenue: 125000,
      fixedMonthlyCosts: 42000,
      variableMonthlyCosts: 31000,
    },
    fields: [
      {
        name: "initialInvestment",
        label: "Inversion inicial requerida",
        kind: "currency",
        step: 5000,
        helper: "Capital necesario para arrancar o expandir.",
      },
      {
        name: "estimatedMonthlyRevenue",
        label: "Ingresos mensuales estimados",
        kind: "currency",
        step: 1000,
        helper: "Facturacion esperada por mes.",
      },
      {
        name: "fixedMonthlyCosts",
        label: "Costos fijos mensuales",
        kind: "currency",
        step: 1000,
        helper: "Nomina, renta y otros costos recurrentes.",
      },
      {
        name: "variableMonthlyCosts",
        label: "Costos variables mensuales",
        kind: "currency",
        step: 1000,
        helper: "Costos que cambian segun el nivel de operacion.",
      },
    ],
    calculate: calculateBusinessFeasibility,
  },
];
